// This file contains the code to generate the baseHTML code 
//and employee cards within that HTML
// we sue the string generated by VS cdoe using the shortcut =>  html:5

// base HTML

    let beginHTML = [
        `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!- - Adding content here from web to get icons and card presentation utilities - ->
        <link rel="stylesheet" href="./assets/css/style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
        <!- - end of extra contant - ->
        <title>Document</title>
    </head>
    <body>
        <nav>
            <div class="navCls" id="navId">
                <h1 class="center">Team profile</h1><span><i class="material-icons" style="font-size: 4.2rem;">&nbsp;&nbsp;members</i></span>
            </div>
        </nav>
    
        <div class="container">    
            
            <div class="row">
    
               `
    ];


// add manager
const addMgrCard = (empl) => {

    let mgrCard = `
                <!-- mgr card  -->
                <div class="col s12 m6 l4">
                    <div class="card small">
                        <div class="content mgr">
                            <span class="title">${empl.Name}</span>
                            <p><span><i class="material-icons">business_center</i></span>&nbsp;&nbsp;&nbsp;${empl.Role}</p>
                        </div>
                        <div class="data">
                            <div class="id ">
                                <span>ID: </span><span>${empl.Id}</span>
                            </div>
                            <div class="">
                                <span>Email: </span><a href="mailto:${empl.Email}">${empl.Email}</a>
                            </div>
                            <div class="">
                                <span>Office: </span><span>${empl.OfficeNum}</span>
                            </div>
                        </div>
                    </div>
                </div>
                `;

    beginHTML.push(mgrCard);

    return beginHTML;

}
// add engineer//
const addEngCard = (empl) => {

    let engCard = `
                <!-- engineer card  -->
                <div class="col s12 m6 l4">
                    <div class="card small">
                        <div class="content eng">
                            <span class="title">${empl.Name}</span>
                            <p><span><i class="material-icons">build</i></span>&nbsp;&nbsp;&nbsp;${empl.Role}</p>
                        </div>
                        <div class="data">
                            <div class="id">
                                <span>ID: </span><span>${empl.Id}</span>
                            </div>
                            <div>
                                <span>Email: </span><a href="mailto:${empl.Email}">${empl.Email}</a>
                            </div>
                            <div>
                                <span>GitHub: </span><a href="https://github.com/${empl.Github}" target="_blank">${empl.Github}</a>
                            </div>
                        </div>
                    </div>
                </div>
    `;

    beginHTML.push(engCard);

    return beginHTML;
}

// add intern
let addInternCard = (empl) => {
    let internCard = `
    <!-- intern card  -->
    <div class="col s12 m6 l4">
        <div class="card small">
            <div class="content intern">
                <span class="title">${empl.Name}</span>
                <p><span><i class="material-icons">lightbulb</i></span>&nbsp;&nbsp;&nbsp;${empl.Role}</p>
            </div>
            <div class="data">
                <div class="id">
                    <span>ID: </span><span>${empl.Id}</span>
                </div>
                <div>
                    <span>Email: </span><a href="mailto:${empl.Email}">${empl.Email}</a>
                </div>
                <div>
                    <span>School: </span><span>${empl.School}</span>
                </div>
            </div>
        </div>
    </div>
    `
    beginHTML.push(internCard);

    return beginHTML;
    
}
// function to add end code to close HTML entries
let addEndHTML = () => {


    let endHTML = `
            </div>
                    
            </div> 

            <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        </body>
        </html>
            `
    beginHTML.push(endHTML);
    return beginHTML;
}

module.exports = {
    beginHTML,
    addMgrCard,
    addEngCard,
    addInternCard,
    addEndHTML
}
